import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Amplify } from 'aws-amplify';
import "./globals.css";
import config from '../aws-exports.js';
import { TiendaProvider } from "./context/tiendaProvider";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

Amplify.configure(config);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <TiendaProvider>
      <html lang="es">
        <Head>
          <link rel="stylesheet" href="https://necolas.github.io/normalize.css/8.0.1/normalize.css" />
        </Head>
        <body className={inter.className}>{children}</body>
      </html>
    </TiendaProvider>
    
  );
}
